# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o2_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Game',
        ),
    ]
