# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o2_api', '0002_auto_20160126_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Game',
            new_name='User_Use_Game',
        ),
    ]
